apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-07-08T04:43:42Z"
  generateName: weave-net-
  labels:
    controller-revision-hash: 6768fc7ccf
    name: weave-net
    pod-template-generation: "1"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.128.0.56"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    time: "2020-09-02T13:21:58Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
        f:labels:
          .: {}
          f:controller-revision-hash: {}
          f:name: {}
          f:pod-template-generation: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"393cf828-c4d0-4965-8265-e9225cfa0c23"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:affinity:
          .: {}
          f:nodeAffinity:
            .: {}
            f:requiredDuringSchedulingIgnoredDuringExecution:
              .: {}
              f:nodeSelectorTerms: {}
        f:containers:
          k:{"name":"weave"}:
            .: {}
            f:command: {}
            f:env:
              .: {}
              k:{"name":"HOSTNAME"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:fieldRef:
                    .: {}
                    f:apiVersion: {}
                    f:fieldPath: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:readinessProbe:
              .: {}
              f:failureThreshold: {}
              f:httpGet:
                .: {}
                f:host: {}
                f:path: {}
                f:port: {}
                f:scheme: {}
              f:periodSeconds: {}
              f:successThreshold: {}
              f:timeoutSeconds: {}
            f:resources:
              .: {}
              f:requests:
                .: {}
                f:cpu: {}
            f:securityContext:
              .: {}
              f:privileged: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/host/etc"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/host/home"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/host/opt"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/host/var/lib/dbus"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/lib/modules"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/run/xtables.lock"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/weavedb"}:
                .: {}
                f:mountPath: {}
                f:name: {}
          k:{"name":"weave-npc"}:
            .: {}
            f:env:
              .: {}
              k:{"name":"HOSTNAME"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:fieldRef:
                    .: {}
                    f:apiVersion: {}
                    f:fieldPath: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources:
              .: {}
              f:requests:
                .: {}
                f:cpu: {}
            f:securityContext:
              .: {}
              f:privileged: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/run/xtables.lock"}:
                .: {}
                f:mountPath: {}
                f:name: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:hostNetwork: {}
        f:hostPID: {}
        f:priorityClassName: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext:
          .: {}
          f:seLinuxOptions: {}
        f:serviceAccount: {}
        f:serviceAccountName: {}
        f:terminationGracePeriodSeconds: {}
        f:tolerations: {}
        f:volumes:
          .: {}
          k:{"name":"cni-bin"}:
            .: {}
            f:hostPath:
              .: {}
              f:path: {}
              f:type: {}
            f:name: {}
          k:{"name":"cni-bin2"}:
            .: {}
            f:hostPath:
              .: {}
              f:path: {}
              f:type: {}
            f:name: {}
          k:{"name":"cni-conf"}:
            .: {}
            f:hostPath:
              .: {}
              f:path: {}
              f:type: {}
            f:name: {}
          k:{"name":"dbus"}:
            .: {}
            f:hostPath:
              .: {}
              f:path: {}
              f:type: {}
            f:name: {}
          k:{"name":"lib-modules"}:
            .: {}
            f:hostPath:
              .: {}
              f:path: {}
              f:type: {}
            f:name: {}
          k:{"name":"weavedb"}:
            .: {}
            f:hostPath:
              .: {}
              f:path: {}
              f:type: {}
            f:name: {}
          k:{"name":"xtables-lock"}:
            .: {}
            f:hostPath:
              .: {}
              f:path: {}
              f:type: {}
            f:name: {}
      f:status:
        f:conditions:
          k:{"type":"Ready"}:
            f:lastTransitionTime: {}
            f:status: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-10-12T05:03:27Z"
  name: weave-net-984k4
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: weave-net
    uid: 393cf828-c4d0-4965-8265-e9225cfa0c23
  resourceVersion: "765294"
  selfLink: /api/v1/namespaces/kube-system/pods/weave-net-984k4
  uid: e7de0648-2511-4b5c-a242-19d638ee6dbd
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - node2-hlf-k8s-rhel-uscentral1a-n12
  containers:
  - command:
    - /home/weave/launch.sh
    env:
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    image: docker.io/weaveworks/weave-kube:2.6.5
    imagePullPolicy: IfNotPresent
    name: weave
    readinessProbe:
      failureThreshold: 3
      httpGet:
        host: 127.0.0.1
        path: /status
        port: 6784
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      requests:
        cpu: 10m
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /weavedb
      name: weavedb
    - mountPath: /host/opt
      name: cni-bin
    - mountPath: /host/home
      name: cni-bin2
    - mountPath: /host/etc
      name: cni-conf
    - mountPath: /host/var/lib/dbus
      name: dbus
    - mountPath: /lib/modules
      name: lib-modules
    - mountPath: /run/xtables.lock
      name: xtables-lock
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: weave-net-token-mkn2g
      readOnly: true
  - env:
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    image: docker.io/weaveworks/weave-npc:2.6.5
    imagePullPolicy: IfNotPresent
    name: weave-npc
    resources:
      requests:
        cpu: 10m
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /run/xtables.lock
      name: xtables-lock
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: weave-net-token-mkn2g
      readOnly: true
  dnsPolicy: ClusterFirstWithHostNet
  enableServiceLinks: true
  hostNetwork: true
  hostPID: true
  nodeName: node2-hlf-k8s-rhel-uscentral1a-n12
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    seLinuxOptions: {}
  serviceAccount: weave-net
  serviceAccountName: weave-net
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/network-unavailable
    operator: Exists
  volumes:
  - hostPath:
      path: /var/lib/weave
      type: ""
    name: weavedb
  - hostPath:
      path: /opt
      type: ""
    name: cni-bin
  - hostPath:
      path: /home
      type: ""
    name: cni-bin2
  - hostPath:
      path: /etc
      type: ""
    name: cni-conf
  - hostPath:
      path: /var/lib/dbus
      type: ""
    name: dbus
  - hostPath:
      path: /lib/modules
      type: ""
    name: lib-modules
  - hostPath:
      path: /run/xtables.lock
      type: FileOrCreate
    name: xtables-lock
  - name: weave-net-token-mkn2g
    secret:
      defaultMode: 420
      secretName: weave-net-token-mkn2g
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-07-08T04:43:42Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-10-12T05:03:27Z"
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-09-02T13:21:58Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-07-08T04:43:42Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://1889f3c0f9c409fb318d3a24faf34d51dae0dfe41b2307efd85ab423561c27e0
    image: weaveworks/weave-kube:2.6.5
    imageID: docker-pullable://weaveworks/weave-kube@sha256:703a045a58377cb04bc85d0f5a7c93356d5490282accd7e5b5d7a99fe2ef09e2
    lastState:
      terminated:
        containerID: docker://3a3e270d8c8144fbefc292c8600cac1eb6e30f8ed14322acc2524a9ab0b3ec26
        exitCode: 4
        finishedAt: "2020-09-02T13:21:39Z"
        reason: Error
        startedAt: "2020-09-02T13:21:38Z"
    name: weave
    ready: true
    restartCount: 36
    started: true
    state:
      running:
        startedAt: "2020-09-02T13:21:52Z"
  - containerID: docker://33f69a97ccb2135ed2f346f4a10ee5c0a42200734fb2c9586967f013c97a1db9
    image: weaveworks/weave-npc:2.6.5
    imageID: docker-pullable://weaveworks/weave-npc@sha256:0f6166e000faa500ccc0df53caae17edd3110590b7b159007a5ea727cdfb1cef
    lastState:
      terminated:
        containerID: docker://81a784139213930e4f52546396f3a1b10fd24dc513f6b9037846bd6f7423b65c
        exitCode: 1
        finishedAt: "2020-08-29T21:01:10Z"
        reason: Error
        startedAt: "2020-08-29T20:49:32Z"
    name: weave-npc
    ready: true
    restartCount: 19
    started: true
    state:
      running:
        startedAt: "2020-09-02T13:21:38Z"
  hostIP: 10.128.0.56
  phase: Running
  podIP: 10.128.0.56
  podIPs:
  - ip: 10.128.0.56
  qosClass: Burstable
  startTime: "2020-07-08T04:43:42Z"
